query GetAdminByUserName($username: String = "") {
    admin(where: {username: {_eq: $username}}) {
        id
        password
    }
}


mutation InsertAdmin($password: String = "", $username: String = "") {
    insert_admin(objects: {password: $password, username: $username}) {
        returning {
            id
            password
        }
    }
}
